/*
PRINT HELLO WORLD IN C PROGRAMMING
*/

// PREPROCESSOR OF DIRECTIVE HEADER FILE 
#include <stdio.h>

// HEADING OF THE MAIN() FUNCTION 
int main (void) {
    // OUTPUT WILL BE DISPLAYED BY PRINTF() FUNCTION METHODS
    printf("Hello World"); // OUTPUT STATEMENT
    return 0; // IT INDICATES THAT  PROGRAM IS EXECUTED SUCCESSFULLY
}